spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
server:
  port: 80
cloud:
  aws:
    credentials:
      access-key: qC3FEGclG9Kefj6GgQs1j8K0aMyFKMfY
      secret-key: xDNE7v7TuiNqYfdFJ1UrzbZwC73NrubH
    s3:
      bucket: weatheroutfit
    region:
      static: ap-northeast-2
    stack:
      auto: false

